/**
 * Redline — pure data model + serializer for the "redline + direct edit"
 * feature. A redline session captures numbered change requests (and in-place
 * text edits) drawn over the live preview, then exports an annotated PNG plus
 * an agent-optimized markdown changelog.
 *
 * This module is intentionally side-effect free: no React, no Tauri `invoke`,
 * no `new Date()` inside the serializers. Everything that varies (timestamps,
 * the export date) is threaded in so `buildMarkdown` / `exportSlug` are
 * deterministic and unit-testable.
 *
 * The element-identity types come from the visual editor: `ElementSignature`
 * is the clicked-element snapshot, and `Location` (the source `file:line:col`)
 * is re-exported here under the contract name so callers import both from one
 * place.
 */

import type { ElementSignature, SourceLocation } from './edit';

/** The source location a redline annotation resolved to, from the visual
 *  editor's className/text resolver (the exact `file:line` in the running dev
 *  server). Re-exported under the contract name `Location`. */
export type Location = SourceLocation;

export type { ElementSignature };

/**
 * A redundant, AI-friendly description of the DOM element a redline points at,
 * captured once at pick time (never a live element reference — that would break
 * on SPA re-render). Each field gives an agent an independent way to relocate
 * the element when the running dev server can't be trusted.
 */
export interface RedlineLocator {
  tag: string;
  id: string | null;
  classList: string[];
  role: string | null;
  ariaLabel: string | null;
  /** Trimmed textContent, capped at ~120 characters. */
  textSnippet: string | null;
  /** Every `data-*` attribute on the element. */
  dataAttributes: Record<string, string>;
  /** Class lists of the element's ancestors, for disambiguation. */
  ancestorClasses: string[];
  /** Text describing the nearest landmark region. */
  nearbyLandmark: string | null;
}

/** Which kind of redline an annotation is: a free-form change request, or an
 *  in-place text replacement (with verbatim old/new text). */
export type RedlineKind = 'change' | 'textedit';

/** A single numbered redline. `change` carries a label; `textedit` carries the
 *  verbatim before/after text and is the heart of that request. */
export interface RedlineAnnotation {
  id: string;
  /** 1-based; resequenced on every add/delete so numbers stay contiguous. */
  number: number;
  kind: RedlineKind;
  /** The requested change, free-form. Empty until the user types a label. */
  label: string;
  /** Snapshot of the clicked element from the visual editor. */
  signature: ElementSignature;
  /** Redundant DOM locator, captured at pick time. */
  locator: RedlineLocator;
  /** Where the element resolved in source, or null if unresolved. */
  resolvedLocation: Location | null;
  /** How the source match was reached, e.g. "unique" | "tag" | "ancestor". */
  confidence?: string;
  /** The marker's bounding box, viewport coordinates. */
  rect: { top: number; left: number; width: number; height: number };
  /** Verbatim text before the edit (textedit only). */
  oldText?: string;
  /** Verbatim text after the edit (textedit only). */
  newText?: string;
  /** True when the edited element held inline markup to preserve (textedit). */
  hasInlineMarkup?: boolean;
  createdAt: string;
}

/** A page's worth of redline annotations plus the page context they target. */
export interface RedlineDocument {
  schemaVersion: 1;
  projectPath: string;
  pageUrl: string;
  pageTitle: string;
  viewport: { width: number; height: number; dpr: number };
  annotations: RedlineAnnotation[];
  createdAt: string;
  updatedAt: string;
}

/**
 * Renumber annotations to 1..N in array order. Returns a new document (and new
 * annotation objects) — never mutates the input — so React state updates stay
 * referentially honest. Call after any add or delete.
 */
export function resequence(doc: RedlineDocument): RedlineDocument {
  const annotations = doc.annotations.map((a, i) => ({ ...a, number: i + 1 }));
  return { ...doc, annotations };
}

// ───────────────────────────── Markdown export ──────────────────────────────

/**
 * Render the document as an agent-optimized change-request markdown file.
 *
 * Deterministic: uses `doc.createdAt` for the captured timestamp (never
 * `new Date()`), so the same document always serializes byte-for-byte the same.
 *
 * `pngFilename` is the sibling screenshot the numbered markers were burned into.
 */
export function buildMarkdown(doc: RedlineDocument, pngFilename: string): string {
  const changes = doc.annotations;
  const out: string[] = [];

  out.push('# Redline Change Request');
  out.push('');
  out.push('> Generated by Ship Studio Redline. Each numbered item below is a');
  out.push('> requested change to the page. The attached screenshot shows the');
  out.push('> same numbers as visual markers.');
  out.push('');
  out.push('| Field | Value |');
  out.push('| --- | --- |');
  out.push(`| Page | ${cell(doc.pageTitle)} |`);
  out.push(`| URL | ${cell(doc.pageUrl)} |`);
  out.push(`| Captured | ${formatDate(doc.createdAt)} |`);
  out.push(`| Viewport | ${doc.viewport.width}x${doc.viewport.height} @ ${doc.viewport.dpr}x |`);
  out.push(`| Screenshot | ${cell(pngFilename)} |`);
  out.push(`| Changes | ${changes.length} |`);
  out.push('');
  out.push('## How to apply');
  out.push('');
  out.push('1. Open the screenshot to see each numbered marker in context.');
  out.push('2. A Source line is the exact file:line resolved from the running dev');
  out.push('   server — trust it first; the selector/locator are fallbacks.');
  out.push('3. When there is no Source line, find the element from the Element');
  out.push('   context, current text, id, and data attributes. Modern sites hash');
  out.push('   their class names (Tailwind, CSS modules, styled-components), so the');
  out.push('   Selector may not appear verbatim in the source.');
  out.push('4. For a text replacement (Change type: text replacement), search the');
  out.push('   source for the exact Old text string and replace it with the New');
  out.push('   text. That is more reliable than the selector. Fall back to the');
  out.push('   selector only if the Old text is not found verbatim, for instance');
  out.push('   when it is interpolated, split across lines, or a translation key.');
  out.push('5. Make the change. Keep it minimal and scoped to the request.');
  out.push('6. Report per item: Done / Skipped (reason) / Needs clarification.');
  out.push('');
  out.push('## Changes');
  out.push('');

  if (changes.length === 0) {
    out.push('_No labeled changes were captured._');
    out.push('');
  }
  for (const change of changes) {
    if (change.kind === 'textedit') {
      appendTextEdit(out, change);
    } else {
      const label = change.label.trim() || '(no label)';
      out.push(`### ${change.number}. ${label}`);
      out.push('');
      out.push(`- Requested change: ${change.label.trim() || '(none given)'}`);
    }
    appendSource(out, change.resolvedLocation, change.confidence);
    appendLocator(out, change.locator);
    out.push('');
  }

  out.push('---');
  out.push(`*${changes.length} change(s) · Ship Studio Redline · schema v${doc.schemaVersion}*`);
  out.push('');
  return out.join('\n');
}

/** Emit the trusted `Source: file:line` line when the element resolved. */
function appendSource(out: string[], location: Location | null, confidence?: string): void {
  if (!location) return;
  const conf = confidence ? ` (${confidence})` : '';
  out.push(`- Source: ${location.file}:${location.line}${conf}`);
}

/** Append a text-replacement change: the verbatim before and after text. */
function appendTextEdit(out: string[], change: RedlineAnnotation): void {
  out.push(`### ${change.number}. Text edit`);
  out.push('');
  out.push('- Change type: text replacement');
  // JSON-encode so quotes/newlines in the copy survive exactly (round-trippable);
  // for plain text this is identical to wrapping the value in double quotes.
  out.push(`- Old text: ${JSON.stringify(change.oldText ?? '')}`);
  out.push(`- New text: ${JSON.stringify(change.newText ?? '')}`);
  if (change.hasInlineMarkup) {
    out.push(
      '- Contains inline markup: yes. The element holds child elements ' +
        '(a link, bold text, an icon). Replace the text and keep that ' +
        'markup intact.'
    );
  }
}

/** Append the redundant DOM locator fields for an element. */
function appendLocator(out: string[], loc: RedlineLocator): void {
  out.push(`- Element: ${describeElement(loc)}`);
  if (loc.textSnippet) out.push(`- Current text: "${loc.textSnippet}"`);
  if (loc.ancestorClasses.length > 0) {
    out.push(`- Ancestor classes: ${loc.ancestorClasses.join(' > ')}`);
  }
  const data = Object.entries(loc.dataAttributes);
  if (data.length > 0) {
    out.push(`- Data attributes: ${data.map(([k, v]) => `${k}="${v}"`).join(', ')}`);
  }
  if (loc.nearbyLandmark) out.push(`- Nearby landmark: ${loc.nearbyLandmark}`);
}

/** Render an element as an opening tag plus its role/aria notes. */
function describeElement(loc: RedlineLocator): string {
  const attrs: string[] = [];
  if (loc.id) attrs.push(`id="${loc.id}"`);
  if (loc.classList.length > 0) attrs.push(`class="${loc.classList.join(' ')}"`);
  const openTag = `<${loc.tag}${attrs.length > 0 ? ' ' + attrs.join(' ') : ''}>`;
  const notes: string[] = [];
  if (loc.role) notes.push(`role: ${loc.role}`);
  if (loc.ariaLabel) notes.push(`aria-label: "${loc.ariaLabel}"`);
  return notes.length > 0 ? `\`${openTag}\` (${notes.join(', ')})` : `\`${openTag}\``;
}

/** Escape a value for use inside a markdown table cell. */
function cell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();
}

/** Format an ISO timestamp as `YYYY-MM-DD HH:MM` (UTC-agnostic; uses the local
 *  fields of the parsed Date). Returns the input unchanged if unparseable. */
function formatDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(
    d.getHours()
  )}:${pad(d.getMinutes())}`;
}

// ───────────────────────────── Export slug ──────────────────────────────────

/** Two-digit zero-padded number. */
function pad(n: number): string {
  return String(n).padStart(2, '0');
}

/** Reduce a string to lowercase, hyphen-separated, filename-safe characters. */
function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Build the export slug: `{YYYY-MM-DD}_{domain}_{path}_redline`. The screenshot
 * and changelog share this slug (`.png` / `.md`).
 *
 * `date` is REQUIRED (no default) so the slug is deterministic — callers pass
 * the document's date explicitly rather than relying on wall-clock time.
 *
 * The path segment keeps exports from different pages of one site distinct, so
 * a single folder can hold a whole batch without filename collisions.
 */
export function exportSlug(pageUrl: string, date: Date): string {
  const datePart = `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
  let domain = 'page';
  let pathPart = 'home';
  try {
    const url = new URL(pageUrl);
    domain = url.hostname.replace(/^www\./, '') || 'page';
    const path = slugify(url.pathname);
    if (path) pathPart = path.slice(0, 40).replace(/-+$/g, '');
  } catch {
    /* malformed URL: keep the defaults */
  }
  const safeDomain = domain.replace(/[^a-z0-9.-]/gi, '-').replace(/\./g, '-');
  return `${datePart}_${safeDomain}_${pathPart}_redline`;
}
