//! # The command manifest
//!
//! One list, two transports. `generate_handler!` builds the Tauri IPC handler
//! for the desktop app; `ship_web_commands!` builds the HTTP route table for
//! the self-hosted server. Keeping them behind a single macro means a command
//! cannot be registered on one transport and silently missing from the other.
//!
//! Adding a command? Add it here and mark the function `#[ship_command]`.

/// Invoke `$m!` with every registered command path.
///
/// `$m` is an `ident`, not a `path`: a macro cannot be invoked through a `path`
/// fragment, so callers import the callback macro by name first.
#[macro_export]
macro_rules! ship_commands {
    ($m:ident) => {
        $m![
            // Git & Prerequisites
            crate::commands::git::check_prerequisites,
            crate::commands::git::get_shipstudio_dir,
            crate::commands::git::ensure_shipstudio_dir,
            crate::commands::git::init_git_repo,
            crate::commands::git::check_git_has_changes,
            crate::commands::git::get_changed_files,
            crate::commands::git::get_file_diff,
            crate::commands::git::get_branch_status,
            crate::commands::git::reset_to_branch,
            crate::commands::git::list_branches,
            crate::commands::git::get_current_branch,
            crate::commands::git::switch_branch,
            crate::commands::git::get_stash_info,
            crate::commands::git::apply_stash,
            crate::commands::git::drop_stash,
            crate::commands::git::stash_changes,
            crate::commands::git::discard_changes,
            crate::commands::git::commit_changes,
            crate::commands::git::create_branch,
            crate::commands::git::push_branch,
            crate::commands::git::get_branch_graph,
            crate::commands::git::get_default_base_branch,
            crate::commands::git::set_default_base_branch,
            crate::commands::git::fetch_all_branches,
            crate::commands::git::git_pull,
            crate::commands::git::pull_and_merge,
            crate::commands::git::delete_branch,
            crate::commands::git::get_backups,
            crate::commands::git::restore_backup,
            // Projects
            crate::commands::projects::list_projects,
            crate::commands::projects::get_dashboard_projects,
            crate::commands::projects::list_pages,
            crate::commands::projects::open_in_finder,
            crate::commands::projects::read_project_metadata,
            crate::commands::projects::write_project_metadata,
            crate::commands::projects::mark_project_opened,
            crate::commands::projects::has_vercel_config,
            crate::commands::projects::get_branch_prefix_preference,
            crate::commands::projects::set_branch_prefix_preference,
            crate::commands::projects::ensure_gitignore_has_shipstudio,
            crate::commands::projects::create_blank_project,
            crate::commands::projects::remove_git_history,
            crate::commands::projects::delete_project,
            crate::commands::projects::remove_project_from_app,
            crate::commands::projects::rename_project,
            crate::commands::projects::clear_project_cache,
            crate::commands::projects::get_auto_accept_mode,
            crate::commands::projects::set_auto_accept_mode,
            crate::commands::projects::get_hide_main_branch_warning,
            crate::commands::projects::set_hide_main_branch_warning,
            crate::commands::projects::get_custom_dev_command,
            crate::commands::projects::set_custom_dev_command,
            crate::commands::projects::get_dev_server_port,
            crate::commands::projects::set_dev_server_port,
            crate::commands::projects::get_force_static_serve,
            crate::commands::projects::set_force_static_serve,
            crate::commands::projects::get_workspace_subpath,
            crate::commands::projects::set_workspace_subpath,
            crate::commands::projects::check_dependencies_installed,
            crate::commands::edit::resolve_classname_source,
            crate::commands::edit::apply_classname_edit,
            crate::commands::edit::apply_classname_edit_multi,
            crate::commands::edit::insert_class_attr,
            crate::commands::edit::resolve_text_source,
            crate::commands::edit::apply_text_edit,
            crate::commands::edit::resolve_image_source,
            crate::commands::edit::apply_src_edit,
            crate::commands::edit::find_component_usage,
            crate::commands::edit::resolve_element_html,
            crate::commands::edit::apply_element_html,
            crate::commands::edit::detect_breakpoints,
            crate::commands::edit::is_tailwind_active,
            crate::commands::edit::project_uses_react,
            crate::commands::edit_structure::insert_element,
            crate::commands::edit_structure::duplicate_element,
            crate::commands::edit_structure::delete_element,
            crate::commands::edit_css::resolve_css_rule,
            crate::commands::edit_css::set_css_declaration,
            crate::commands::edit_css::create_css_class,
            crate::commands::edit_css::list_stylesheets,
            crate::commands::edit_css::list_css_classes,
            crate::commands::edit_css::list_css_selectors,
            crate::commands::edit_css::get_css_variables,
            crate::commands::edit_css::list_css_variables,
            crate::commands::edit_css::locate_css_rules,
            crate::commands::edit_css::apply_css_rule_text,
            crate::commands::edit_css::delete_css_rule,
            crate::commands::edit_css::wrap_css_rule,
            crate::commands::edit_css::rename_css_selector,
            crate::commands::edit_css::rename_css_at_rule,
            crate::commands::custom_classes::detect_tailwind_setup,
            crate::commands::custom_classes::list_custom_classes,
            crate::commands::custom_classes::create_custom_class,
            crate::commands::custom_classes::update_custom_class,
            crate::commands::custom_classes::delete_custom_class,
            crate::commands::custom_classes::classify_apply_tokens,
            crate::commands::projects::get_terminal_state,
            crate::commands::projects::set_terminal_state,
            crate::commands::projects::move_project_to_account,
            crate::commands::projects::get_project_account_id,
            crate::commands::projects::extract_template_zip,
            crate::commands::projects::export_project_as_template,
            crate::commands::projects::open_project_in_new_window,
            crate::commands::projects::register_project_for_window,
            crate::commands::projects::unregister_project_from_window,
            crate::commands::projects::get_project_window,
            crate::commands::projects::focus_window_by_label,
            // Pinned projects (background sessions rail)
            crate::commands::projects::pin_project,
            crate::commands::projects::unpin_project,
            crate::commands::projects::list_pinned_projects,
            crate::commands::projects::reorder_pins,
            crate::commands::projects::save_pin_session,
            crate::commands::projects::get_pin_session,
            // Project session lifecycle (background sessions rail)
            crate::commands::projects::register_project_session,
            crate::commands::projects::suspend_project_session,
            crate::commands::projects::unregister_project_session,
            crate::commands::projects::touch_project_session,
            crate::commands::projects::list_project_sessions,
            crate::commands::projects::get_project_session_info,
            crate::commands::projects::get_active_session_count,
            crate::commands::projects::get_session_memory,
            // Internationalization (i18n)
            crate::commands::i18n::get_i18n_status,
            crate::commands::i18n::set_i18n_config,
            // Environment variables
            crate::commands::env::list_env_files,
            crate::commands::env::read_env_file,
            crate::commands::env::write_env_file,
            crate::commands::env::create_env_file,
            crate::commands::env::delete_env_file,
            // IDE & Webviews
            crate::commands::ide::check_ide_availability,
            crate::commands::ide::open_in_ide,
            crate::commands::ide::check_browser_availability,
            crate::commands::ide::open_url_in_browser,
            crate::commands::ide::create_preview_webview,
            crate::commands::ide::navigate_preview_webview,
            crate::commands::ide::resize_preview_webview,
            crate::commands::ide::destroy_preview_webview,
            crate::commands::ide::eval_preview_js,
            crate::commands::ide::scroll_preview_webview,
            crate::commands::ide::get_preview_scroll_info,
            crate::commands::ide::check_preview_can_scroll,
            crate::commands::ide::open_studio_window,
            crate::commands::ide::capture_project_thumbnail,
            crate::commands::ide::capture_fullpage_playwright,
            crate::commands::ide::capture_viewport_playwright,
            crate::commands::ide::get_project_thumbnail,
            crate::commands::ide::upload_project_thumbnail,
            crate::commands::ide::get_screenshot_base64,
            crate::commands::ide::crop_and_save_screenshot,
            crate::commands::ide::compare_screenshots,
            crate::commands::ide::stitch_screenshots,
            // Analytics
            crate::commands::analytics::track_event,
            crate::commands::analytics::identify_user,
            crate::commands::analytics::get_analytics_enabled,
            crate::commands::analytics::set_analytics_enabled,
            crate::commands::analytics::get_device_id_command,
            // Settings
            crate::commands::settings::get_calendar_hidden,
            crate::commands::settings::set_calendar_hidden,
            crate::commands::settings::get_slack_cta_hidden,
            crate::commands::settings::set_slack_cta_hidden,
            crate::commands::settings::get_terminal_gpu_enabled,
            crate::commands::settings::set_terminal_gpu_enabled,
            crate::commands::settings::get_thumbnails_enabled,
            crate::commands::settings::set_thumbnails_enabled,
            // Accounts (Workspaces)
            crate::commands::accounts::list_accounts,
            crate::commands::accounts::create_account,
            crate::commands::accounts::update_account,
            crate::commands::accounts::delete_account,
            crate::commands::accounts::get_active_account_id,
            crate::commands::accounts::set_active_account_id,
            crate::commands::accounts::get_account_credential_status,
            crate::commands::accounts::set_account_credential,
            crate::commands::accounts::clear_account_credential,
            crate::commands::accounts::claude_connect_start,
            crate::commands::accounts::claude_connect_write,
            crate::commands::accounts::claude_connect_resize,
            crate::commands::accounts::claude_connect_close,
            crate::commands::accounts::disconnect_claude_account,
            crate::commands::accounts::workspace_connect_start,
            crate::commands::accounts::workspace_connect_write,
            crate::commands::accounts::workspace_connect_resize,
            crate::commands::accounts::workspace_connect_close,
            crate::commands::accounts::workspace_disconnect_service,
            // Projects folder
            crate::commands::settings::get_projects_root,
            crate::commands::settings::set_projects_root,
            crate::commands::settings::is_custom_projects_root,
            crate::commands::settings::pick_projects_root,
            crate::commands::projects::list_movable_projects,
            crate::commands::projects::move_projects_to_root,
            // AI generation
            crate::commands::ai::generate_pr_description,
            crate::commands::ai::generate_commit_message,
            // Claude integration
            crate::commands::claude::check_claude_cli_status,
            crate::commands::claude::install_claude_cli,
            crate::commands::claude::claude_session_exists,
            // Shopify theme integration
            crate::commands::shopify::check_shopify_cli_status,
            crate::commands::shopify::get_shopify_store,
            crate::commands::shopify::set_shopify_store,
            crate::commands::shopify::kill_stale_theme_dev,
            // Claude skills
            crate::commands::skills::list_claude_skills,
            crate::commands::skills::check_skills_cli,
            crate::commands::skills::search_skills,
            crate::commands::skills::install_skill,
            crate::commands::skills::remove_skill,
            // MCP servers
            crate::commands::mcp::list_mcp_servers,
            crate::commands::mcp::add_mcp_server,
            crate::commands::mcp::remove_mcp_server,
            // Plugins
            crate::commands::plugins::list_plugins,
            crate::commands::plugins::install_plugin,
            crate::commands::plugins::uninstall_plugin,
            crate::commands::plugins::update_plugin,
            crate::commands::plugins::check_plugin_update,
            crate::commands::plugins::read_plugin_bundle,
            crate::commands::plugins::read_plugin_manifest,
            crate::commands::plugins::toggle_plugin,
            crate::commands::plugins::exec_plugin_shell,
            crate::commands::plugins::read_plugin_storage,
            crate::commands::plugins::write_plugin_storage,
            crate::commands::plugins::link_dev_plugin,
            crate::commands::plugins::unlink_dev_plugin,
            // GitHub integration
            crate::commands::github::check_github_cli_status,
            crate::commands::github::get_github_username,
            crate::commands::github::get_github_orgs,
            crate::commands::github::get_project_github_status,
            crate::commands::github::push_to_github,
            crate::commands::github::list_github_repos,
            crate::commands::github::list_collaborator_repos,
            crate::commands::github::detect_package_manager,
            // Publishing
            crate::commands::publishing::publish_to_github,
            crate::commands::publishing::publish_to_staging,
            crate::commands::publishing::publish_to_production,
            crate::commands::publishing::publish_branch,
            // Pull requests
            crate::commands::pull_requests::list_pull_requests,
            crate::commands::pull_requests::create_pull_request,
            crate::commands::pull_requests::merge_pull_request,
            crate::commands::pull_requests::checkout_pull_request,
            crate::commands::pull_requests::close_pull_request,
            // Merge conflict resolution
            crate::commands::conflicts::get_conflict_info,
            crate::commands::conflicts::resolve_conflict,
            crate::commands::conflicts::abort_merge,
            crate::commands::conflicts::complete_merge,
            // Preview Proxy
            crate::commands::proxy::start_preview_proxy,
            crate::commands::proxy::stop_preview_proxy,
            crate::commands::proxy::probe_dev_server,
            // Static File Server
            crate::commands::static_server::start_static_server,
            crate::commands::static_server::stop_static_server,
            // Agent Preview Bridge (MCP server for the workspace agent)
            crate::commands::agent_bridge::get_agent_bridge_url,
            crate::commands::agent_bridge::get_agent_bridge_active_url,
            crate::commands::agent_bridge::register_cursor_mcp,
            crate::commands::agent_bridge::agent_bridge_attach,
            crate::commands::agent_bridge::agent_bridge_respond,
            // Project Type Detection
            crate::commands::projects::detect_project_type_command,
            crate::commands::projects::project_path_exists,
            // Native Mobile Preview (iOS Simulator via serve-sim)
            crate::commands::mobile::list_booted_simulators,
            crate::commands::mobile::start_mobile_preview,
            crate::commands::mobile::get_simulator_launch_command,
            crate::commands::mobile::simulator_app_running,
            crate::commands::mobile::hide_simulator,
            crate::commands::mobile::list_android_devices,
            crate::commands::mobile::android_app_running,
            crate::commands::mobile::detect_mobile_targets,
            crate::commands::mobile::mobile_platform_support,
            crate::commands::mobile::set_mobile_launch_status,
            // PTY & Terminal
            crate::commands::pty::spawn_pty,
            crate::commands::pty::kill_pty,
            crate::commands::pty::kill_window_pty,
            crate::commands::pty::kill_all_pty,
            crate::commands::pty::cleanup_orphaned_processes,
            crate::commands::pty::kill_port,
            crate::commands::pty::find_available_port,
            crate::commands::pty::find_and_reserve_port,
            crate::commands::pty::get_reserved_port_for_window,
            crate::commands::pty::release_reserved_port,
            crate::commands::pty::get_shell_path,
            crate::commands::pty::get_system_env,
            crate::commands::pty::register_external_pty,
            crate::commands::pty::unregister_external_pty,
            crate::commands::pty::kill_project_pty,
            crate::commands::pty::get_project_pty_pids,
            // Backend-owned PTY sessions (phase 3)
            crate::commands::pty_session::pty_session_open,
            crate::commands::pty_session::pty_session_write,
            crate::commands::pty_session::pty_session_resize,
            crate::commands::pty_session::pty_session_kill,
            crate::commands::pty_session::pty_session_attach,
            crate::commands::pty_session::pty_session_detach,
            crate::commands::pty_session::pty_session_list,
            // Community Templates
            crate::commands::templates::fetch_community_templates,
            crate::commands::templates::download_template_zip,
            // Setup/Onboarding
            crate::commands::setup::get_full_setup_status,
            crate::commands::setup::resolve_cli_path,
            crate::commands::setup::install_homebrew,
            crate::commands::setup::install_node_via_brew,
            crate::commands::setup::install_git_via_brew,
            crate::commands::setup::install_gh_via_brew,
            crate::commands::setup::install_brew_packages,
            crate::commands::setup::install_winget_packages,
            crate::commands::setup::start_github_auth,
            crate::commands::setup::start_claude_auth,
            crate::commands::setup::check_claude_auth_status,
            crate::commands::setup::check_npm_cache_permissions,
            crate::commands::setup::cleanup_auth_processes,
            crate::commands::setup::get_system_arch,
            crate::commands::setup::install_version,
            crate::commands::setup::quick_setup_check,
            crate::commands::setup::get_onboarding_test_mode,
            crate::commands::setup::mock_mark_setup_item_ready,
            crate::commands::setup::set_external_agent_opt_in,
            crate::commands::setup::set_default_host,
            crate::commands::setup::get_default_host,
            crate::commands::setup::ensure_agent_workdir,
            crate::commands::setup::mark_setup_complete,
            crate::commands::setup::reset_setup_state,
            crate::commands::setup::get_default_agent_id,
            crate::commands::setup::set_default_agent_id,
            crate::commands::setup::get_agents_status,
            crate::commands::setup::sign_out_agent,
            crate::commands::setup::uninstall_agent,
            // Client Editor
            // Code Browser
            crate::commands::code::list_project_files,
            crate::commands::code::read_project_file,
            crate::commands::code::save_project_file,
            // Assets
            crate::commands::assets::get_assets_root,
            crate::commands::assets::set_assets_root,
            crate::commands::assets::list_assets,
            crate::commands::assets::upload_asset,
            crate::commands::assets::delete_asset,
            crate::commands::assets::rename_asset,
            crate::commands::assets::create_asset_folder,
            crate::commands::assets::export_asset,
            // Code Health
            crate::commands::health::detect_health_scripts,
            crate::commands::health::run_health_script,
            crate::commands::health::get_health_status,
            crate::commands::health::clear_health_status,
            crate::commands::health::get_package_json,
            // External Projects
            crate::commands::external_projects::register_external_project,
            crate::commands::external_projects::unregister_external_project,
            crate::commands::external_projects::is_project_external,
            crate::commands::external_projects::ensure_external_project_registered,
            // Attached Libraries
            crate::commands::attached_libraries::list_attached_libraries,
            crate::commands::attached_libraries::attached_library_dirs,
            crate::commands::attached_libraries::add_attached_library,
            crate::commands::attached_libraries::remove_attached_library,
            // Monorepo
            crate::commands::monorepo::detect_workspaces,
            // Folders
            crate::commands::folders::list_folders,
            crate::commands::folders::create_folder,
            crate::commands::folders::rename_folder,
            crate::commands::folders::delete_folder,
            crate::commands::folders::add_project_to_folder,
            crate::commands::folders::remove_project_from_folder,
            crate::commands::folders::move_project_to_folder,
            crate::commands::folders::get_project_folder,
            crate::commands::folders::get_filed_project_paths,
            crate::commands::folders::get_folder_projects,
            crate::commands::folders::get_folder,
            // Support (cStar) — identity signing only; tickets use ChatClient SDK
            crate::commands::support::get_support_identity,
            // Logging
            crate::logging::get_log_path,
            crate::logging::log_frontend_event,
            // Snapshots / Undo-Redo
            crate::commands::snapshots::snapshot_start_watching,
            crate::commands::snapshots::snapshot_stop_watching,
            crate::commands::snapshots::snapshot_status,
            crate::commands::snapshots::snapshot_undo,
            crate::commands::snapshots::snapshot_redo,
            // Window / Compact Mode
            crate::commands::window::enter_compact_mode,
            crate::commands::window::exit_compact_mode,
            crate::commands::window::set_always_on_top,
            crate::commands::window::save_compact_position,
            crate::commands::window::get_compact_preferences,
            crate::commands::window::set_compact_expanded,
            crate::commands::window::get_window_position,
            crate::commands::window::set_window_position,
            crate::commands::window::start_window_drag,
            crate::commands::window::focus_window,
            crate::commands::window::set_window_title,
            // Clipboard (Windows terminal paste)
            crate::commands::clipboard::read_clipboard_text,
            crate::commands::clipboard::stage_clipboard_image,
        ]
    };
}
